# Generated by Django 4.0.6 on 2022-07-26 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
