# Generated by Django 4.0.6 on 2022-07-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_information_author_delete_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='series',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Series',
        ),
    ]
