# Generated by Django 4.0.6 on 2022-07-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_books_series_delete_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='author',
            field=models.CharField(default='author', max_length=50),
        ),
    ]
