# Generated by Django 4.0.6 on 2022-07-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_information_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
