# Generated by Django 4.0.6 on 2022-07-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test_field',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
