# Generated by Django 4.0.6 on 2022-07-10 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='test_field',
        ),
    ]
