# Generated by Django 4.0.6 on 2022-08-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('history', models.TextField()),
                ('date', models.DateTimeField()),
                ('image_history', models.ImageField(upload_to='uploads')),
            ],
        ),
    ]
