# Generated by Django 4.0.6 on 2022-08-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='image_history',
            field=models.ImageField(blank=True, default='', upload_to='hitory/image'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image_services',
            field=models.ImageField(blank=True, default='', upload_to='services/image'),
        ),
    ]
