# Generated by Django 4.0.6 on 2022-08-12 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_history_image_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='subtitle',
        ),
    ]
