# Generated by Django 4.0.6 on 2022-07-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brend', models.TextField(verbose_name='Бренд')),
                ('article', models.TextField(verbose_name='Артикл')),
                ('quantity', models.TextField(verbose_name='Количество')),
                ('cost', models.TextField(verbose_name='Цена')),
            ],
        ),
    ]
