# Generated by Django 4.0.6 on 2022-07-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0004_product_cross'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.TextField(unique=True, verbose_name='Артикул'),
        ),
    ]
