# Generated by Django 4.0.6 on 2022-07-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0005_alter_product_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.TextField(verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cross',
            field=models.TextField(unique=True, verbose_name='Кросс'),
        ),
    ]
