# Generated by Django 4.0.6 on 2022-07-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0006_alter_product_article_alter_product_cross'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cross',
            field=models.TextField(verbose_name='Кросс'),
        ),
    ]
