# Generated by Django 4.0.6 on 2022-07-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0008_alter_product_cross'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parsing_date',
            field=models.DateTimeField(verbose_name='Дата парсинга'),
            preserve_default=False,
        ),
    ]
