# Generated by Django 4.0.6 on 2022-08-02 17:05

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Category', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='City', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name', max_length=20)),
                ('last_name', models.CharField(help_text='Last name', max_length=20)),
                ('email', models.EmailField(help_text='E-mail', max_length=254, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Phone number', max_length=128, region=None, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, editable=False, help_text='Item status')),
                ('name', models.CharField(help_text='Short name for item', max_length=200)),
                ('type', models.CharField(choices=[('l', 'lost'), ('f', 'found')], default='f', help_text='Item type', max_length=1)),
                ('description', models.TextField(blank=True, help_text='Description for item', max_length=1000)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, default='images/items/default_item.png', help_text='Photo of item', upload_to='images/items')),
                ('category', models.ForeignKey(help_text='Item category', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.city')),
                ('who_found', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='who_found', to='catalog.contact')),
                ('who_lost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='who_lost', to='catalog.contact')),
            ],
        ),
    ]
