# Generated by Django 4.0.6 on 2022-08-02 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_item_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(help_text='Item category', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category', to='catalog.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='city',
            field=models.ForeignKey(help_text='City', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='city', to='catalog.city'),
        ),
    ]
