# Generated by Django 4.0.6 on 2022-08-09 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0003_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('phone', models.CharField(max_length=50, verbose_name='phone')),
                ('data', models.DateField(auto_now_add=True, verbose_name='data')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.services', verbose_name='Services')),
            ],
        ),
    ]
