# Generated by Django 4.0.6 on 2022-08-11 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='services',
            new_name='service',
        ),
    ]
