# Generated by Django 4.0.6 on 2022-07-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=9)),
                ('auto', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=4)),
                ('service', models.CharField(max_length=200)),
                ('comment', models.TextField()),
            ],
        ),
    ]
