# Generated by Django 4.0.6 on 2022-07-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='auto',
            field=models.CharField(max_length=200, verbose_name='Марка и модель авто'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='comment',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.PositiveIntegerField(max_length=9, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='service',
            field=models.CharField(max_length=200, verbose_name='Услуги'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='year',
            field=models.CharField(max_length=4, verbose_name='Год авто'),
        ),
    ]
