# Generated by Django 4.0.6 on 2022-07-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sto', '0002_alter_registration_auto_alter_registration_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.PositiveIntegerField(verbose_name='Телефон'),
        ),
    ]
