# Generated by Django 4.0.6 on 2022-07-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sto', '0004_alter_registration_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='Телефон'),
        ),
    ]
