with open ('D:/Мое/Мое/Python/text.txt', 'r+') as f:    
    print(f.read())
    f.seek(0)

while True:
    n = int(input("Please, enter the maximum number of characters in line from 35 to 50\n"))
    if  n < 34 and n < 51:
        print("The number is not correct")
        continue 
    break 
print("Look at the text")
                       
with open ('D:/Мое/Мое/Python/text.txt', 'r+')  as f:   
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
   print(f.read(n))
buffer = 10
with open('D:/Мое/Мое/Python/text.txt', 'r') as f:
    with open('D:/Мое/Мое/Python/text-Copy.txt', 'w') as copy:
        s = f.read(buffer)
        while s:
            copy.write(s)
            s = f.read(buffer)  
    print('We have created a copy of text')       